import { initializeApp } from 'firebase/app';
import { getFirestore, doc, setDoc } from 'firebase/firestore';
import fs from 'fs';
import dotenv from 'dotenv';

dotenv.config({ path: '.env.local' });

const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY,
  authDomain: process.env.FIREBASE_AUTH_DOMAIN,
  projectId: process.env.FIREBASE_PROJECT_ID,
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.FIREBASE_APP_ID
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const attendances = JSON.parse(fs.readFileSync('data/attendances.json', 'utf8'));
console.log('Uploading ' + attendances.length + ' records to Firebase...');

async function upload() {
  let count = 0;
  for (const att of attendances) {
    // Only upload records generated by system (has reason or specific date)
    // Actually just upload all to be safe and override if exists
    await setDoc(doc(db, 'attendances', att.id), att);
    count++;
    if (count % 50 === 0) console.log(`Uploaded ${count}/${attendances.length}`);
  }
  console.log('Done uploading to Firebase!');
  process.exit(0);
}

upload();
